/*
 * evalParameters.hpp
 *
 *  Created on: Feb 3, 2017
 *      Author: vabi
 */

#ifndef LIB_DEFINES_EVALPARAMETERS_HPP_
#define LIB_DEFINES_EVALPARAMETERS_HPP_

#define BISHOPPAIR 50
#define ROOKONOPENFILE 15
#define ISOLATEDPAWN   -10
#define ISOLATEDDOUBLEPAWN -50
#define NONISOLATEDDOUBLEPAWN -20

#endif /* LIB_DEFINES_EVALPARAMETERS_HPP_ */
