/*
 * pieceCombinations.hpp
 *
 *  Created on: Jun 29, 2018
 *      Author: vabi
 */

#ifndef LIB_DEFINES_PIECECOMBINATIONS_HPP_
#define LIB_DEFINES_PIECECOMBINATIONS_HPP_

#define KINGSPRESENT (BIT64(20) | BIT64(32+20))

#define WHITEKRK (KINGSPRESENT | BIT64(12))
#define BLACKKRK (KINGSPRESENT | BIT64(12+32))

#define WHITEKBBK (KINGSPRESENT | BIT64(9))
#define BLACKKBBK (KINGSPRESENT | BIT64(9+32))

#define WHITEKBPK (KINGSPRESENT | BIT64(8) | BIT64(0))
#define BLACKKBPK (KINGSPRESENT | BIT64(8+32) | BIT64(32))

#define WHITEKPK (KINGSPRESENT |  BIT64(0))
#define BLACKKPK (KINGSPRESENT | BIT64(32))

#define WHITEKBNK (KINGSPRESENT | BIT64(8) | BIT64(4))
#define BLACKKBNK (KINGSPRESENT | BIT64(40) | BIT64(36))

#define KBKB     (KINGSPRESENT | BIT64(8) | BIT64(40))

#endif /* LIB_DEFINES_PIECECOMBINATIONS_HPP_ */
