/*
 * nonSliderMoveTables.hpp
 *
 *  Created on: Aug 11, 2017
 *      Author: vabi
 */

#ifndef LIB_MOVEGENERATION_NONSLIDERMOVETABLES_HPP_
#define LIB_MOVEGENERATION_NONSLIDERMOVETABLES_HPP_

#include <stdint.h>
#include <lib/Defines/knightmoves.hpp>
#include <lib/Defines/kingMoves.hpp>
#include <assert.h>
#include <lib/basics.hpp>

class nonSliderMoveTables {
    uint64_t knightmovetables[64] = { KNIGHTMOVES0, KNIGHTMOVES1, KNIGHTMOVES2, KNIGHTMOVES3, KNIGHTMOVES4, KNIGHTMOVES5, KNIGHTMOVES6, KNIGHTMOVES7, KNIGHTMOVES8, KNIGHTMOVES9, KNIGHTMOVES10, KNIGHTMOVES11, KNIGHTMOVES12, KNIGHTMOVES13, KNIGHTMOVES14, KNIGHTMOVES15, KNIGHTMOVES16, KNIGHTMOVES17, KNIGHTMOVES18, KNIGHTMOVES19, KNIGHTMOVES20, KNIGHTMOVES21, KNIGHTMOVES22, KNIGHTMOVES23, KNIGHTMOVES24, KNIGHTMOVES25, KNIGHTMOVES26, KNIGHTMOVES27, KNIGHTMOVES28, KNIGHTMOVES29, KNIGHTMOVES30, KNIGHTMOVES31, KNIGHTMOVES32, KNIGHTMOVES33, KNIGHTMOVES34, KNIGHTMOVES35, KNIGHTMOVES36, KNIGHTMOVES37, KNIGHTMOVES38, KNIGHTMOVES39, KNIGHTMOVES40, KNIGHTMOVES41, KNIGHTMOVES42, KNIGHTMOVES43, KNIGHTMOVES44, KNIGHTMOVES45, KNIGHTMOVES46, KNIGHTMOVES47, KNIGHTMOVES48, KNIGHTMOVES49, KNIGHTMOVES50, KNIGHTMOVES51, KNIGHTMOVES52, KNIGHTMOVES53, KNIGHTMOVES54, KNIGHTMOVES55, KNIGHTMOVES56, KNIGHTMOVES57, KNIGHTMOVES58, KNIGHTMOVES59, KNIGHTMOVES60, KNIGHTMOVES61, KNIGHTMOVES62, KNIGHTMOVES63 };
    uint64_t kingmovetables[64] = { KINGMOVES0, KINGMOVES1, KINGMOVES2, KINGMOVES3, KINGMOVES4, KINGMOVES5, KINGMOVES6, KINGMOVES7, KINGMOVES8, KINGMOVES9, KINGMOVES10, KINGMOVES11, KINGMOVES12, KINGMOVES13, KINGMOVES14, KINGMOVES15, KINGMOVES16, KINGMOVES17, KINGMOVES18, KINGMOVES19, KINGMOVES20, KINGMOVES21, KINGMOVES22, KINGMOVES23, KINGMOVES24, KINGMOVES25, KINGMOVES26, KINGMOVES27, KINGMOVES28, KINGMOVES29, KINGMOVES30, KINGMOVES31, KINGMOVES32, KINGMOVES33, KINGMOVES34, KINGMOVES35, KINGMOVES36, KINGMOVES37, KINGMOVES38, KINGMOVES39, KINGMOVES40, KINGMOVES41, KINGMOVES42, KINGMOVES43, KINGMOVES44, KINGMOVES45, KINGMOVES46, KINGMOVES47, KINGMOVES48, KINGMOVES49, KINGMOVES50, KINGMOVES51, KINGMOVES52, KINGMOVES53, KINGMOVES54, KINGMOVES55, KINGMOVES56, KINGMOVES57, KINGMOVES58, KINGMOVES59, KINGMOVES60, KINGMOVES61, KINGMOVES62, KINGMOVES63 };

 public:
    uint64_t getKingMove(uint16_t field) const{
    #ifdef DEBUG
          assert(field < 64);
    #endif
          return kingmovetables[field];
    }

    uint64_t getKnightMove(uint16_t field) const{
    #ifdef DEBUG
          assert(field < 64);
    #endif
          return knightmovetables[field];
    }

};

extern const nonSliderMoveTables moveTables;

__attribute__((always_inline)) static inline uint64_t getKingMoves(uint16_t field) {
    return moveTables.getKingMove(field);
}

__attribute__((always_inline)) static inline uint64_t getKnightMoves(uint16_t field) {
    return moveTables.getKnightMove(field);
}

__attribute__((always_inline)) static inline uint64_t getNonSliderMoves(uint16_t field, figureType type) {
    if(king == type) {
        return getKingMoves(field);
    } else {
#ifdef DEBUG
        assert(knight == type);
#endif
        return getKnightMoves(field);
    }
}


#endif /* LIB_MOVEGENERATION_NONSLIDERMOVETABLES_HPP_ */
